const brandActionTypes = {
  GET_ALL_REQUEST: 'GET_ALL_BRANDS_REQUEST',
  GET_ALL_SUCCESS: 'GET_ALL_BRANDS_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_BRANDS_FAILURE',

  GET_ONE_REQUEST: 'GET_ONE_BRAND_REQUEST',
  GET_ONE_SUCCESS: 'GET_ONE_BRAND_SUCCESS',
  GET_ONE_FAILURE: 'GET_ONE_BRAND_FAILURE',

  CREATE_REQUEST: 'CREATE_BRAND_REQUEST',
  CREATE_SUCCESS: 'CREATE_BRAND_SUCCESS',
  CREATE_FAILURE: 'CREATE_BRAND_FAILURE',

  UPDATE_REQUEST: 'UPDATE_BRAND_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_BRAND_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_BRAND_FAILURE',
  
  DELETE_REQUEST: 'DELETE_BRAND_REQUEST',
  DELETE_SUCCESS: 'DELETE_BRAND_SUCCESS',
  DELETE_FAILURE: 'DELETE_BRAND_FAILURE',

  CHANGE_CURRENT_PAGE: 'BRANDS_CHANGE_CURRENT_PAGE',

  CHANGE_ITEMS_PER_PAGE: 'BRANDS_CHANGE_ITEMS_PER_PAGE',

  UPDATE_SEARCH_PHRASE: 'BRANDS_UPDATE_SEARCH_PHRASE',
};

export default brandActionTypes;