version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - '3080:3080'
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    environment:
      DB_URI: mysqldb://mysqldb:27017/my-climbing-rack
    depends_on:
      - mysqldb
  react-ui:
    build:
      context: ./client
    ports:
      - '3000:3000'
    container_name: react-client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3389:3306
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my-climbing-rack
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mongodb_data_container:
