version: '3'
services:
  nodejs-api:
    build:
      context: ./api
    ports:
      - '3080:3080'
    volumes:
      - ./api:/usr/src/app/api
    environment:
      DB_URI: mysqldb://root:asd123@localhost:3306/my-climbing-rack
    depends_on:
      - mysqldb
    networks:
      - my_climbing_rack
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  react-client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
    networks:
      - my_climbing_rack
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3389:3306'
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my-climbing-rack-dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - my_climbing_rack
  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25
    networks:
      - my_climbing_rack

volumes:
  mongodb_data_container:

networks:
  my_climbing_rack:
    external:
      name: my_climbing_rack