const authActionTypes = {
  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LOGOUT: 'AUTH_LOGOUT',
  
  VERIFY_EMAIL_REQUEST: 'AUTH_VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_SUCCESS: 'AUTH_VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'AUTH_VERIFY_EMAIL_FAILURE',

  CLEAR_ERRORS: 'AUTH_CLEAR_ERRORS',
};

export default authActionTypes;