const authActionTypes = {
  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LOGOUT: 'AUTH_LOGOUT',
  
  VERIFY_EMAIL_REQUEST: 'AUTH_VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_SUCCESS: 'AUTH_VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'AUTH_VERIFY_EMAIL_FAILURE',
  
  FORGOT_PASSWORD_REQUEST: 'AUTH_FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'AUTH_FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'AUTH_FORGOT_PASSWORD_FAILURE',
  
  VALIDATE_RESET_TOKEN_REQUEST: 'AUTH_VALIDATE_RESET_TOKEN_REQUEST',
  VALIDATE_RESET_TOKEN_SUCCESS: 'AUTH_VALIDATE_RESET_TOKEN_SUCCESS',
  VALIDATE_RESET_TOKEN_FAILURE: 'AUTH_VALIDATE_RESET_TOKEN_FAILURE',
  
  RESET_PASSWORD_REQUEST: 'AUTH_RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'AUTH_RESET_PASSWORD_FAILURE',

  CLEAR_ERRORS: 'AUTH_CLEAR_ERRORS',
};

export default authActionTypes;