const ListActionTypes = {
  GET_ALL_LISTS_REQUEST: 'GET_ALL_LISTS_REQUEST',
  GET_ALL_LISTS_SUCCESS: 'GET_ALL_LISTS_SUCCESS',
  GET_ALL_LISTS_FAILURE: 'GET_ALL_LISTS_FAILURE',
  GET_ONE_LIST_REQUEST: 'GET_ONE_LIST_REQUEST',
  GET_ONE_LIST_SUCCESS: 'GET_ONE_LIST_SUCCESS',
  GET_ONE_LIST_FAILURE: 'GET_ONE_LIST_FAILURE',
  CREATE_LIST_REQUEST: 'CREATE_LIST_REQUEST',
  CREATE_LIST_SUCCESS: 'CREATE_LIST_SUCCESS',
  CREATE_LIST_FAILURE: 'CREATE_LIST_FAILURE',
  UPDATE_LIST_REQUEST: 'UPDATE_LIST_REQUEST',
  UPDATE_LIST_SUCCESS: 'UPDATE_LIST_SUCCESS',
  UPDATE_LIST_FAILURE: 'UPDATE_LIST_FAILURE',
  DELETE_LIST_REQUEST: 'DELETE_LIST_REQUEST',
  DELETE_LIST_SUCCESS: 'DELETE_LIST_SUCCESS',
  DELETE_LIST_FAILURE: 'DELETE_LIST_FAILURE',
};

export default ListActionTypes;