const GearActionTypes = {
  GET_ALL_GEARS_REQUEST: 'GET_ALL_GEARS_REQUEST',
  GET_ALL_GEARS_SUCCESS: 'GET_ALL_GEARS_SUCCESS',
  GET_ALL_GEARS_FAILURE: 'GET_ALL_GEARS_FAILURE',
  GET_ONE_GEAR_REQUEST: 'GET_ONE_GEAR_REQUEST',
  GET_ONE_GEAR_SUCCESS: 'GET_ONE_GEAR_SUCCESS',
  GET_ONE_GEAR_FAILURE: 'GET_ONE_GEAR_FAILURE',
  CREATE_GEAR_REQUEST: 'CREATE_GEAR_REQUEST',
  CREATE_GEAR_SUCCESS: 'CREATE_GEAR_SUCCESS',
  CREATE_GEAR_FAILURE: 'CREATE_GEAR_FAILURE',
  UPDATE_GEAR_REQUEST: 'UPDATE_GEAR_REQUEST',
  UPDATE_GEAR_SUCCESS: 'UPDATE_GEAR_SUCCESS',
  UPDATE_GEAR_FAILURE: 'UPDATE_GEAR_FAILURE',
  DELETE_GEAR_REQUEST: 'DELETE_GEAR_REQUEST',
  DELETE_GEAR_SUCCESS: 'DELETE_GEAR_SUCCESS',
  DELETE_GEAR_FAILURE: 'DELETE_GEAR_FAILURE',
};

export default GearActionTypes;