const SetActionTypes = {
  GET_ALL_SETS_REQUEST: 'GET_ALL_SETS_REQUEST',
  GET_ALL_SETS_SUCCESS: 'GET_ALL_SETS_SUCCESS',
  GET_ALL_SETS_FAILURE: 'GET_ALL_SETS_FAILURE',
  GET_ONE_SET_REQUEST: 'GET_ONE_SET_REQUEST',
  GET_ONE_SET_SUCCESS: 'GET_ONE_SET_SUCCESS',
  GET_ONE_SET_FAILURE: 'GET_ONE_SET_FAILURE',
  CREATE_SET_REQUEST: 'CREATE_SET_REQUEST',
  CREATE_SET_SUCCESS: 'CREATE_SET_SUCCESS',
  CREATE_SET_FAILURE: 'CREATE_SET_FAILURE',
  UPDATE_SET_REQUEST: 'UPDATE_SET_REQUEST',
  UPDATE_SET_SUCCESS: 'UPDATE_SET_SUCCESS',
  UPDATE_SET_FAILURE: 'UPDATE_SET_FAILURE',
  DELETE_SET_REQUEST: 'DELETE_SET_REQUEST',
  DELETE_SET_SUCCESS: 'DELETE_SET_SUCCESS',
  DELETE_SET_FAILURE: 'DELETE_SET_FAILURE',
};

export default SetActionTypes;